# -*- coding: utf-8 -*-
"""CSE6207_Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qzx-YoMGeOfdZCciqovD1_XGiMrE1MYi

# CSE 6207 — Day 1
## Environment, Dataset & Fault-Injection Pipeline

**Goal of today:** get everything running *before* writing a model line.
By the end you will have:
1. A working GPU runtime with MedMNIST + the official MedMNIST-C corruption API.
2. PneumoniaMNIST (64×64) loaded and explored.
3. A fault-injection pipeline using the **official** MedMNIST-C registry (not hand-rolled corruptions).
4. Saved clean↔corrupted image pairs — the training data for the recovery module on Day 4.
5. A reusable checkpoint utility (Colab sessions time out; never lose a run).

**Resolution note:** we work at **64×64**. It is large enough for corruptions (blur, JPEG) to be visible and for the pretrained MobileNetV2 to be useful, but small enough that overnight training on free Colab is fast. Absolute accuracy will not be directly comparable to the MedMNIST-C paper (they use 224); our *relative* findings — collapse, recovery gain, Pareto curve — are what matter and hold regardless.

> **Before you start:** Runtime → Change runtime type → **GPU** (T4 is fine).

### 1 — Install dependencies
The `medmnistc` package is the official corruption API from the MedMNIST-C paper (Di Salvo et al., 2024).
"""

# medmnist = datasets; medmnistc = official corruption registry/API
!pip install -q medmnist
!pip install -q git+https://github.com/francescodisalvo05/medmnistc-api.git
!pip install -q torchmetrics  # for PSNR/SSIM later in the week

import torch
print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU ONLY — set Runtime>GPU")

"""### 2 — Mount Google Drive (checkpoints & saved pairs)
Everything we save goes here so a session timeout never costs you a run.
"""

from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_DIR = '/content/drive/MyDrive/cse6207'
CKPT_DIR    = os.path.join(PROJECT_DIR, 'checkpoints')
PAIRS_DIR   = os.path.join(PROJECT_DIR, 'pairs')        # corrupted<->clean pairs for Day 4
FIG_DIR     = os.path.join(PROJECT_DIR, 'figures')
for d in (PROJECT_DIR, CKPT_DIR, PAIRS_DIR, FIG_DIR):
    os.makedirs(d, exist_ok=True)
print("Project dir ready:", PROJECT_DIR)

"""### 3 — Reusable checkpoint utility
Use this all week. Saves model + optimizer + epoch so you can resume an interrupted overnight job.
"""

import torch, os

def save_ckpt(path, model, optimizer=None, epoch=0, extra=None):
    payload = {"model": model.state_dict(), "epoch": epoch}
    if optimizer is not None:
        payload["optimizer"] = optimizer.state_dict()
    if extra:
        payload["extra"] = extra
    torch.save(payload, path)
    print(f"saved -> {path} (epoch {epoch})")

def load_ckpt(path, model, optimizer=None, map_location=None):
    if not os.path.exists(path):
        print("no checkpoint at", path, "-> starting fresh")
        return 0
    ck = torch.load(path, map_location=map_location)
    model.load_state_dict(ck["model"])
    if optimizer is not None and "optimizer" in ck:
        optimizer.load_state_dict(ck["optimizer"])
    print(f"loaded <- {path} (epoch {ck.get('epoch',0)})")
    return ck.get("epoch", 0)

# quick sanity test
_m = torch.nn.Linear(2, 2)
save_ckpt(os.path.join(CKPT_DIR, "_smoke.pt"), _m, epoch=0)
load_ckpt(os.path.join(CKPT_DIR, "_smoke.pt"), _m)

"""### 4 — Load PneumoniaMNIST (64×64)
MedMNIST ships native multi-resolution variants. We request `size=64` directly — no manual resizing.
"""

import numpy as np
import medmnist
from medmnist import INFO

DATA_FLAG = "pneumoniamnist"
SIZE = 64
info = INFO[DATA_FLAG]
n_classes = len(info["label"])
print("Task:", info["task"], "| classes:", info["label"], "| channels:", info["n_channels"])

DataClass = getattr(medmnist, info["python_class"])
# download=True caches to ~/.medmnist; as_rgb=True gives 3 channels for MobileNetV2 later
train_raw = DataClass(split="train", download=True, size=SIZE, as_rgb=True)
val_raw   = DataClass(split="val",   download=True, size=SIZE, as_rgb=True)
test_raw  = DataClass(split="test",  download=True, size=SIZE, as_rgb=True)

print("train/val/test sizes:", len(train_raw), len(val_raw), len(test_raw))
print("one sample image shape:", np.array(train_raw[0][0]).shape, "label:", train_raw[0][1])

"""### 5 — Explore: class distribution + sample grid
Verify the splits and look for class imbalance (PneumoniaMNIST is imbalanced — note it now, it affects how you read accuracy later).
"""

import numpy as np
import matplotlib.pyplot as plt

def label_counts(ds):
    labels = np.array([int(ds[i][1]) for i in range(len(ds))])
    return {info["label"][str(k)]: int((labels==k).sum()) for k in np.unique(labels)}

for name, ds in [("train", train_raw), ("val", val_raw), ("test", test_raw)]:
    print(name, label_counts(ds))

# sample grid
fig, axes = plt.subplots(2, 6, figsize=(12, 4))
for ax, i in zip(axes.ravel(), range(12)):
    img, lab = train_raw[i]
    ax.imshow(np.array(img))
    ax.set_title(info["label"][str(int(lab))], fontsize=8)
    ax.axis("off")
plt.suptitle("PneumoniaMNIST 64x64 — clean samples")
plt.tight_layout(); plt.show()

"""### 6 — Fault-injection pipeline (official MedMNIST-C registry)
We use the paper's own corruption registry rather than hand-rolling noise/blur, so corruptions are the *exact* ones the benchmark defines, organized by category (noise / blur / digital / …) across severities 1–5.

The cell below probes the installed API for the corruption set tied to PneumoniaMNIST and falls back gracefully if the import path differs between package versions. Run it, read the printed corruption names, and we'll use them in the next cell.
"""

!sudo apt-get update -qq
!sudo apt-get install -y -qq libmagickwand-dev imagemagick
!convert --version | head -1

!pip install -q --force-reinstall wand

from wand.version import MAGICK_VERSION_NUMBER
print("Wand sees ImageMagick:", MAGICK_VERSION_NUMBER)

from medmnistc.corruptions.registry import CORRUPTIONS_DS
from medmnistc.augmentation import AugMedMNISTC

corr_dict = CORRUPTIONS_DS["pneumoniamnist"]
print("number of datasets:", len(CORRUPTIONS_DS))
print("pneumoniamnist corruptions:", list(corr_dict.keys()))
print("one entry structure:", corr_dict[list(corr_dict)[0]])

import inspect
obj = corr_dict["gaussian_noise"]
print("apply signature:", inspect.signature(obj.apply))
print("num severities:", len(obj.severity_params))
print("severity_params:", obj.severity_params)

import numpy as np

def corrupt(pil_img, name, severity):
    """One corruption, fixed severity. severity is 0-indexed: 0=mildest ... 4=strongest."""
    out = corr_dict[name].apply(pil_img.copy(), severity)
    return np.array(out).astype("uint8")

import matplotlib.pyplot as plt, numpy as np

clean_pil = train_raw[0][0]
name = "gaussian_noise"
n_sev = len(corr_dict[name].severity_params)  # 5 levels, indices 0..4

fig, axes = plt.subplots(1, n_sev + 1, figsize=(2.4*(n_sev+1), 3))
axes[0].imshow(np.array(clean_pil)); axes[0].set_title("clean"); axes[0].axis("off")
for s in range(n_sev):                     # 0..4
    axes[s+1].imshow(corrupt(clean_pil, name, s))
    axes[s+1].set_title(f"sev {s}"); axes[s+1].axis("off")
plt.suptitle(f"{name} severity ramp (0=mild, 4=strong)"); plt.tight_layout(); plt.show()

"""**If the cell above printed corruption names**, plug the ones you want into the list below (good X-ray-relevant picks: a noise type, a blur type, and JPEG/pixelate from the digital category). **If it failed**, read the printed submodule list, open that module in the Colab file browser, and copy the correct import — then tell me what it is and I'll patch this cell.

### 7 — Build & save clean↔corrupted pairs (Day 4 training data)
Day 4's recovery autoencoder trains on corrupted→clean pairs. **Generalization guard:** we only generate pairs at severities **1–3** here and reserve severity **5** as an *unseen* test severity (built later). This prevents the module from simply memorizing the corruptions it will be tested on.

We save as compressed `.npz` to Drive so you don't regenerate them every session.
"""

import numpy as np, os
from tqdm import tqdm

TRAIN_SEVERITIES = [1, 2, 3]          # reserve sev 4-5 as unseen
chosen = chosen or "gaussian_noise"   # falls back if you skipped setting it above

def build_pairs(dataset, corruption_name, severities, max_items=None):
    cleans, corrupts = [], []
    n = len(dataset) if max_items is None else min(max_items, len(dataset))
    for i in tqdm(range(n)):
        pil_img = dataset[i][0]
        clean_arr = np.array(pil_img).astype("uint8")
        for s in severities:
            cleans.append(clean_arr)
            corrupts.append(apply_corruption(pil_img, corruption_name, s))
    return np.stack(cleans), np.stack(corrupts)

# start with a subset to confirm it works end-to-end; bump max_items later / overnight
clean_arr, corrupt_arr = build_pairs(train_raw, chosen, TRAIN_SEVERITIES, max_items=500)
print("pairs:", clean_arr.shape, corrupt_arr.shape)

out_path = os.path.join(PAIRS_DIR, f"pairs_{chosen}_sev123_subset.npz")
np.savez_compressed(out_path, clean=clean_arr, corrupt=corrupt_arr,
                    corruption=chosen, severities=np.array(TRAIN_SEVERITIES))
print("saved ->", out_path)

"""### 8 — Deliverable: clean → corrupted comparison grid
This is the Day 1 figure for your showcase. Saved to Drive.
"""

import numpy as np, matplotlib.pyplot as plt, os

N = 5
fig, axes = plt.subplots(2, N, figsize=(2.4*N, 5))
for j in range(N):
    axes[0, j].imshow(clean_arr[j*len(TRAIN_SEVERITIES)]); axes[0, j].axis("off")
    axes[1, j].imshow(corrupt_arr[j*len(TRAIN_SEVERITIES)]); axes[1, j].axis("off")
axes[0, 0].set_ylabel("clean", fontsize=11)
axes[1, 0].set_ylabel(chosen, fontsize=11)
fig.suptitle(f"Day 1 deliverable — clean vs {chosen} (sev {TRAIN_SEVERITIES[0]})")
plt.tight_layout()
fig_path = os.path.join(FIG_DIR, "day1_clean_vs_corrupted.png")
plt.savefig(fig_path, dpi=150, bbox_inches="tight")
plt.show()
print("figure saved ->", fig_path)

"""---
## Day 1 checklist
- [ ] GPU runtime confirmed
- [ ] `medmnist` + `medmnistc` installed
- [ ] Drive mounted; project dirs created
- [ ] Checkpoint utility smoke-tested
- [ ] PneumoniaMNIST 64×64 loaded; class imbalance noted
- [ ] Official corruption registry located (record the correct import path!)
- [ ] Severity ramp visualized
- [ ] Clean↔corrupted pairs (sev 1–3) saved to Drive
- [ ] Comparison grid figure saved

**Hand-off to Day 2:** frozen-classifier baseline (MobileNetV2 on clean data), evaluated on clean + corrupted sev 1/3/5.

> If the corruption-registry cell (§6) failed to auto-locate the API, paste me the printed submodule list and I'll give you the exact import to drop in.
"""



"""# CSE 6207 — Day 2
## Baseline 1: the frozen classifier and its silent collapse

**What we're doing and why.** We train a *normal* pneumonia classifier (MobileNetV2) on **clean** X-rays only, then measure how badly it degrades on **corrupted** X-rays at severities 1/3/5. That degradation — the "silent collapse" — is the problem your whole project claims to solve. It's the floor every later result is measured against.

**The critical rule:** once trained, this classifier is **FROZEN for the entire project**. Your recovery module (Day 4–5) sits in front of *this exact frozen model*. Any accuracy you recover later is then attributable to the recovery module, not to the classifier secretly learning corruptions. This mirrors the prior-art setup (Paper B).

**Deliverable:** a table of accuracy across {clean, sev1, sev3, sev5} showing the collapse, plus a bar chart. Saved to Drive.

> Assumes Day 1 already ran: Drive mounted, `medmnistc` working (ImageMagick fixed), `CORRUPTIONS_DS` importable.
"""

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import numpy as np

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]
to_norm_tensor = T.Compose([T.ToTensor(), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])

class CleanDS(Dataset):
    """Clean images -> normalized tensor."""
    def __init__(self, raw): self.raw = raw
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        return to_norm_tensor(img), int(np.asarray(lab).squeeze())

class CorruptDS(Dataset):
    """Corrupt each image with ONE fixed corruption+severity, then normalize.
       Used only for evaluation."""
    def __init__(self, raw, corruption, severity):
        self.raw, self.c, self.s = raw, corruption, severity
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        cor = Image.fromarray(corrupt(img, self.c, self.s))
        return to_norm_tensor(cor), int(np.asarray(lab).squeeze())

from PIL import Image
BATCH = 128
train_loader = DataLoader(CleanDS(train_raw), batch_size=BATCH, shuffle=True,  num_workers=2)
val_loader   = DataLoader(CleanDS(val_raw),   batch_size=BATCH, shuffle=False, num_workers=2)
test_clean   = DataLoader(CleanDS(test_raw),  batch_size=BATCH, shuffle=False, num_workers=2)
print("loaders ready")

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

import torch.nn as nn
from torchvision import models

def build_mobilenet(n_classes):
    m = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
    m.classifier[1] = nn.Linear(m.classifier[1].in_features, n_classes)
    return m

model = build_mobilenet(n_classes).to(device)
print("params (M):", sum(p.numel() for p in model.parameters())/1e6)

import os
import torch.nn as nn, torch

EPOCHS, LR = 10, 1e-4
opt = torch.optim.Adam(model.parameters(), lr=LR)
crit = nn.CrossEntropyLoss()
BASELINE_CKPT = "/content/baseline1_mobilenet.pt"   # local session, not Drive

@torch.no_grad()
def evaluate(model, loader):
    model.eval(); correct = total = 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        pred = model(x).argmax(1)
        correct += (pred == y).sum().item(); total += y.numel()
    return correct / total

start = 0
if os.path.exists(BASELINE_CKPT):
    ck = torch.load(BASELINE_CKPT, map_location=device)
    model.load_state_dict(ck["model"]); opt.load_state_dict(ck["optimizer"])
    start = ck["epoch"]; print(f"resumed from epoch {start}")

for ep in range(start, EPOCHS):
    model.train()
    for x, y in train_loader:
        x, y = x.to(device), y.to(device)
        opt.zero_grad(); loss = crit(model(x), y); loss.backward(); opt.step()
    acc = evaluate(model, val_loader)
    print(f"epoch {ep+1}/{EPOCHS}  val_acc={acc:.4f}")
    torch.save({"model": model.state_dict(), "optimizer": opt.state_dict(),
                "epoch": ep+1}, BASELINE_CKPT)
print("training done. baseline saved (local) ->", BASELINE_CKPT)

EVAL_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]
EVAL_SEVERITIES  = [0, 2, 4]

results = {}
clean_acc = evaluate(model, test_clean)
results["clean"] = clean_acc
print(f"clean test acc: {clean_acc:.4f}\n")

for c in EVAL_CORRUPTIONS:
    for s in EVAL_SEVERITIES:
        loader = DataLoader(CorruptDS(test_raw, c, s), batch_size=BATCH,
                            shuffle=False, num_workers=2)
        acc = evaluate(model, loader)
        results[f"{c}_sev{s}"] = acc
        print(f"{c:18s} sev{s}: {acc:.4f}  (drop {clean_acc-acc:+.4f})")

import torch, numpy as np
from collections import Counter

@torch.no_grad()
def pred_distribution(model, loader):
    model.eval(); preds = []
    for x, y in loader:
        preds += model(x.to(device)).argmax(1).cpu().tolist()
    return Counter(preds)

# clean vs a corrupted condition
print("clean preds:", pred_distribution(model, test_clean))
loader = DataLoader(CorruptDS(test_raw, "gaussian_noise", 2), batch_size=BATCH, shuffle=False, num_workers=2)
print("noise sev2 preds:", pred_distribution(model, loader))

import numpy as np
from sklearn.metrics import balanced_accuracy_score

@torch.no_grad()
def eval_full(model, loader):
    model.eval(); ys, ps = [], []
    for x, y in loader:
        ps += model(x.to(device)).argmax(1).cpu().tolist()
        ys += y.tolist()
    acc = float(np.mean(np.array(ys) == np.array(ps)))
    bal = float(balanced_accuracy_score(ys, ps))
    return acc, bal

EVAL_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]
EVAL_SEVERITIES  = [0, 2, 4]          # 0-indexed: mild / mid / strong

results = {}
acc, bal = eval_full(model, test_clean)
results["clean"] = {"acc": acc, "bal": bal}
print(f"clean: acc={acc:.4f}  bal={bal:.4f}\n")

for c in EVAL_CORRUPTIONS:
    for s in EVAL_SEVERITIES:
        loader = DataLoader(CorruptDS(test_raw, c, s), batch_size=BATCH, shuffle=False, num_workers=2)
        acc, bal = eval_full(model, loader)
        results[f"{c}_sev{s}"] = {"acc": acc, "bal": bal}
        print(f"{c:18s} sev{s}: acc={acc:.4f}  bal={bal:.4f}")

import pandas as pd

rows = [{"condition": "clean", "severity": -1, "corruption": "-",
         "accuracy": results["clean"]["acc"], "balanced_acc": results["clean"]["bal"]}]
for c in EVAL_CORRUPTIONS:
    for s in EVAL_SEVERITIES:
        r = results[f"{c}_sev{s}"]
        rows.append({"condition": f"{c}_sev{s}", "severity": s, "corruption": c,
                     "accuracy": r["acc"], "balanced_acc": r["bal"]})
df = pd.DataFrame(rows)
csv_path = "/content/baseline1_results.csv"     # local, not Drive
df.to_csv(csv_path, index=False)
print("saved ->", csv_path)
df

import matplotlib.pyplot as plt, numpy as np

labels = ["clean"] + [f"{c}\nsev{s}" for c in EVAL_CORRUPTIONS for s in EVAL_SEVERITIES]
accs = [results["clean"]["acc"]] + [results[f"{c}_sev{s}"]["acc"] for c in EVAL_CORRUPTIONS for s in EVAL_SEVERITIES]
bals = [results["clean"]["bal"]] + [results[f"{c}_sev{s}"]["bal"] for c in EVAL_CORRUPTIONS for s in EVAL_SEVERITIES]

x = np.arange(len(labels)); w = 0.4
fig, ax = plt.subplots(figsize=(11, 4.5))
ax.bar(x - w/2, accs, w, label="raw accuracy", color="#C62828")
ax.bar(x + w/2, bals, w, label="balanced accuracy", color="#1565C0")
ax.axhline(0.5, ls=":", c="gray", alpha=0.7, label="chance (balanced)")
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel("score"); ax.set_ylim(0, 1)
ax.set_title("Baseline 1 — silent collapse (raw accuracy hides it; balanced accuracy reveals it)")
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig("/content/day2_collapse.png", dpi=150, bbox_inches="tight")   # local
plt.show()

"""---
## Day 2 checklist
- [ ] MobileNetV2 trained on clean data; `baseline1_mobilenet.pt` saved (FROZEN from here on)
- [ ] Clean test accuracy recorded
- [ ] Corrupted accuracy at sev 1/3/5 for 3 corruption families recorded
- [ ] `baseline1_results.csv` saved to Drive
- [ ] Collapse bar chart saved

**What this gives you:** the floor. The gap between the green clean bar and the red corrupted bars is exactly what Days 3–5 try to close.

**Hand-off to Day 3:** retrain the *same architecture* with MedMNIST-C augmentation (Paper A's method) — this time using `AugMedMNISTC` with `augmentation=True` for random severity sampling during training — and measure how much of the gap augmentation alone closes. That becomes Baseline 2.

> Note for write-up: we work at 64×64, so absolute accuracy won't match Paper A's 224×224 table. Relative findings (collapse magnitude, recovery gain) are the contribution and hold regardless.

# CSE 6207 — Day 3
## Baseline 2: Paper A's augmentation method (the bar to beat)

**What we're doing and why.** Day 2 showed a clean-trained classifier collapses to chance under corruption. Day 3 replicates the core method of **Paper A (MedMNIST-C, Di Salvo et al. 2024)**: retrain the *same* MobileNetV2 architecture, but inject the official corruptions *during training* as augmentation. Then we re-measure the **exact same collapse table** from Day 2.

**The question this answers:** how much of the collapse does augmentation alone recover? That number is the bar your recovery module (Day 4–5) must beat or complement. If your module only matches this, the contribution is weak — which is exactly why the Day 5 ablation includes a "Recovery + Aug" row.

**Key mechanism difference from Day 2:**
- Day 2 / evaluation: `apply(img, severity)` with `augmentation=False` → *fixed* severity, reproducible test sets.
- Day 3 / training: `AugMedMNISTC(...)` → *randomly samples* corruption + severity each call. This is the whole point of augmentation — the model sees varied corruptions during training so it learns to be robust.

**Deliverable:** the Day 2 table recomputed for the aug-trained model, plus a Baseline1-vs-Baseline2 comparison (recovery gain per corruption).

> Assumes Day 1+2 ran: `medmnistc` working, PneumoniaMNIST loaded, `eval_full`, `CorruptDS`, `corrupt()`, and the frozen `baseline1_results` available. Re-run setup cells if this is a fresh session.
"""

import numpy as np, matplotlib.pyplot as plt
from medmnistc.augmentation import AugMedMNISTC

aug = AugMedMNISTC(train_corruptions=corr_dict)   # per README
sample_pil = train_raw[0][0]

# call it a few times — outputs should differ (random corruption/severity)
fig, axes = plt.subplots(1, 5, figsize=(12, 3))
for i, ax in enumerate(axes):
    out = aug(sample_pil)
    ax.imshow(np.array(out)); ax.set_title(f"aug {i}"); ax.axis("off")
plt.suptitle("AugMedMNISTC — should show DIFFERENT corruptions each call")
plt.tight_layout(); plt.show()
print("output type:", type(aug(sample_pil)))

import torchvision.transforms as T
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import numpy as np

norm = T.Normalize(IMAGENET_MEAN, IMAGENET_STD)
clean_tf = T.Compose([T.ToTensor(), norm])
aug_tf   = T.Compose([AugMedMNISTC(train_corruptions=corr_dict), T.ToTensor(), norm])

class AugTrainDS(Dataset):
    """MedMNIST-C augmented training set (random corruption+severity per sample)."""
    def __init__(self, raw): self.raw = raw
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        return aug_tf(img), int(np.asarray(lab).squeeze())

class CleanDS(Dataset):
    def __init__(self, raw): self.raw = raw
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        return clean_tf(img), int(np.asarray(lab).squeeze())

def corrupt(pil_img, name, severity):
    return np.array(corr_dict[name].apply(pil_img.copy(), severity)).astype("uint8")

class CorruptDS(Dataset):
    def __init__(self, raw, c, s): self.raw, self.c, self.s = raw, c, s
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        cor = Image.fromarray(corrupt(img, self.c, self.s))
        return clean_tf(cor), int(np.asarray(lab).squeeze())

BATCH = 128
aug_train_loader = DataLoader(AugTrainDS(train_raw), batch_size=BATCH, shuffle=True,  num_workers=2)
val_loader       = DataLoader(CleanDS(val_raw),      batch_size=BATCH, shuffle=False, num_workers=2)
test_clean       = DataLoader(CleanDS(test_raw),     batch_size=BATCH, shuffle=False, num_workers=2)
print("loaders ready (training set is now augmented)")

import numpy as np, torch
from sklearn.metrics import balanced_accuracy_score

@torch.no_grad()
def eval_full(model, loader):
    model.eval(); ys, ps = [], []
    for x, y in loader:
        ps += model(x.to(device)).argmax(1).cpu().tolist()
        ys += y.tolist()
    acc = float(np.mean(np.array(ys) == np.array(ps)))
    bal = float(balanced_accuracy_score(ys, ps))
    return acc, bal

from torchvision import models
import torch.nn as nn

def build_mobilenet(n):
    m = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
    m.classifier[1] = nn.Linear(m.classifier[1].in_features, n)
    return m

aug_model = build_mobilenet(n_classes).to(device)
EPOCHS, LR = 10, 1e-4
opt  = torch.optim.Adam(aug_model.parameters(), lr=LR)
crit = nn.CrossEntropyLoss()
AUG_CKPT = "/content/baseline2_aug_mobilenet.pt"

start = 0
if os.path.exists(AUG_CKPT):
    ck = torch.load(AUG_CKPT, map_location=device)
    aug_model.load_state_dict(ck["model"]); opt.load_state_dict(ck["optimizer"]); start = ck["epoch"]
    print("resumed from epoch", start)

for ep in range(start, EPOCHS):
    aug_model.train()
    for x, y in aug_train_loader:
        x, y = x.to(device), y.to(device)
        opt.zero_grad(); loss = crit(aug_model(x), y); loss.backward(); opt.step()
    acc, bal = eval_full(aug_model, val_loader)
    print(f"epoch {ep+1}/{EPOCHS}  val_acc={acc:.4f}  val_bal={bal:.4f}")
    torch.save({"model": aug_model.state_dict(), "optimizer": opt.state_dict(), "epoch": ep+1}, AUG_CKPT)
print("Baseline 2 trained ->", AUG_CKPT)

EVAL_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]
EVAL_SEVERITIES  = [0, 2, 4]

aug_results = {}
acc, bal = eval_full(aug_model, test_clean)
aug_results["clean"] = {"acc": acc, "bal": bal}
print(f"clean: acc={acc:.4f}  bal={bal:.4f}\n")
for c in EVAL_CORRUPTIONS:
    for s in EVAL_SEVERITIES:
        loader = DataLoader(CorruptDS(test_raw, c, s), batch_size=BATCH, shuffle=False, num_workers=2)
        acc, bal = eval_full(aug_model, loader)
        aug_results[f"{c}_sev{s}"] = {"acc": acc, "bal": bal}
        print(f"{c:18s} sev{s}: acc={acc:.4f}  bal={bal:.4f}")

import pandas as pd

# PASTE your Day 2 balanced-accuracy numbers here (from the locked Baseline 1 table):
baseline1_bal = {
    "clean": 0.829915,
    "gaussian_noise_sev0": 0.500000, "gaussian_noise_sev2": 0.500000, "gaussian_noise_sev4": 0.500000,
    "gaussian_blur_sev0": 0.745726,  "gaussian_blur_sev2": 0.502137,  "gaussian_blur_sev4": 0.500000,
    "jpeg_compression_sev0": 0.764957, "jpeg_compression_sev2": 0.678205, "jpeg_compression_sev4": 0.606410,
}

rows = []
for k in baseline1_bal:
    b1 = baseline1_bal[k]
    b2 = aug_results[k]["bal"]
    rows.append({"condition": k, "baseline1_bal": b1, "baseline2_aug_bal": b2,
                 "recovery_gain": b2 - b1})
cmp = pd.DataFrame(rows)
cmp.to_csv("/content/baseline2_comparison.csv", index=False)
print("saved -> /content/baseline2_comparison.csv")
cmp

import numpy as np, torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image

TRAIN_SEVERITIES = [0, 1, 2]     # train recovery on these
HOLDOUT_SEVERITY = 4             # never seen during recovery training
TRAIN_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]

class PairDS(Dataset):
    """Returns (corrupted_tensor, clean_tensor) in [0,1] — NO ImageNet norm.
       The AE works in pixel space; we re-normalize before the classifier later."""
    def __init__(self, raw, corruptions, severities):
        self.raw, self.cs, self.ss = raw, corruptions, severities
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, _ = self.raw[i]
        c = self.cs[np.random.randint(len(self.cs))]
        s = self.ss[np.random.randint(len(self.ss))]
        cor = corrupt(img, c, s)                      # uint8 HxWx3
        clean = np.array(img).astype("uint8")
        to_t = lambda a: torch.from_numpy(a).float().permute(2,0,1) / 255.0
        return to_t(cor), to_t(clean)

pair_train = DataLoader(PairDS(train_raw, TRAIN_CORRUPTIONS, TRAIN_SEVERITIES),
                        batch_size=128, shuffle=True, num_workers=2)
pair_val   = DataLoader(PairDS(val_raw,   TRAIN_CORRUPTIONS, TRAIN_SEVERITIES),
                        batch_size=128, shuffle=False, num_workers=2)
print("pair loaders ready. train severities:", TRAIN_SEVERITIES, "| holdout:", HOLDOUT_SEVERITY)

import torch.nn as nn

class ConvAE(nn.Module):
    """Lightweight conv autoencoder. `width` scales capacity.
       residual=True makes it predict the clean image as (input + correction),
       which strongly protects clean images from being blurred (Paper B failure mode)."""
    def __init__(self, width=16, residual=True):
        super().__init__()
        w = width
        self.residual = residual
        self.enc = nn.Sequential(
            nn.Conv2d(3, w, 3, 2, 1), nn.ReLU(inplace=True),      # 64->32
            nn.Conv2d(w, w*2, 3, 2, 1), nn.ReLU(inplace=True),    # 32->16
        )
        self.dec = nn.Sequential(
            nn.ConvTranspose2d(w*2, w, 4, 2, 1), nn.ReLU(inplace=True),  # 16->32
            nn.ConvTranspose2d(w, 3, 4, 2, 1),                          # 32->64
        )
    def forward(self, x):
        out = self.dec(self.enc(x))
        out = x + out if self.residual else out
        return torch.clamp(out, 0.0, 1.0)

def count_params(m): return sum(p.numel() for p in m.parameters())

# capacity sweep: widths chosen to span ~roughly an order of magnitude in params
SWEEP_WIDTHS = [4, 8, 16, 32]
for w in SWEEP_WIDTHS:
    print(f"width={w:3d}  params={count_params(ConvAE(w)):,}")

import torch, torch.nn as nn
from torchvision import models

def build_mobilenet(n):
    m = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
    m.classifier[1] = nn.Linear(m.classifier[1].in_features, n)
    return m

clf = build_mobilenet(n_classes).to(device)
ck = torch.load("/content/baseline1_mobilenet.pt", map_location=device)
clf.load_state_dict(ck["model"]); clf.eval()
for p in clf.parameters(): p.requires_grad = False
print("frozen Baseline 1 loaded")

IMN_MEAN = torch.tensor([0.485,0.456,0.406], device=device).view(1,3,1,1)
IMN_STD  = torch.tensor([0.229,0.224,0.225], device=device).view(1,3,1,1)
def imagenet_norm(x01): return (x01 - IMN_MEAN) / IMN_STD

import numpy as np, torch
from torch.utils.data import Dataset, DataLoader

TRAIN_SEVERITIES  = [0, 1, 2]
HOLDOUT_SEVERITY  = 4
TRAIN_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]

class PairLabelDS(Dataset):
    def __init__(self, raw, cs, ss): self.raw, self.cs, self.ss = raw, cs, ss
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        c = self.cs[np.random.randint(len(self.cs))]
        s = self.ss[np.random.randint(len(self.ss))]
        cor = corrupt(img, c, s); clean = np.array(img).astype("uint8")
        tt = lambda a: torch.from_numpy(a).float().permute(2,0,1)/255.0
        return tt(cor), tt(clean), int(np.asarray(lab).squeeze())

pl_train = DataLoader(PairLabelDS(train_raw, TRAIN_CORRUPTIONS, TRAIN_SEVERITIES),
                      batch_size=128, shuffle=True, num_workers=2)
print("pair-label loader ready")

import torch, torch.nn as nn

def train_ae_perceptual(width, clf, epochs=10, lr=1e-3, lam_max=1.5, residual=False):
    ae = ConvAE(width, residual=residual).to(device)
    opt = torch.optim.Adam(ae.parameters(), lr=lr)
    mse = nn.MSELoss(); ce = nn.CrossEntropyLoss()
    clf.eval()
    for ep in range(epochs):
        lam = 0.0 if ep < 2 else lam_max * (ep-1)/(epochs-2)
        ae.train(); run=0; n=0
        for cor, clean, lab in pl_train:
            cor, clean, lab = cor.to(device), clean.to(device), lab.to(device)
            out = ae(cor)
            loss = mse(out, clean) + lam*ce(clf((out-IMN_MEAN)/IMN_STD), lab)
            opt.zero_grad(); loss.backward(); opt.step()
            run += loss.item()*cor.size(0); n += cor.size(0)
        print(f"  [w={width}] ep{ep+1} lam={lam:.2f} loss={run/n:.4f}")
    return ae

aes = {}
for w in SWEEP_WIDTHS:
    print(f"perceptual-training AE width={w} ({count_params(ConvAE(w)):,} params)")
    aes[w] = train_ae_perceptual(w, clf, residual=False)
    torch.save(aes[w].state_dict(), f"/content/ae_perc_w{w}.pt")
print("all perceptual AE variants trained")

import torch, numpy as np, matplotlib.pyplot as plt
from torchmetrics.functional import peak_signal_noise_ratio as psnr_fn
from torchmetrics.functional import structural_similarity_index_measure as ssim_fn

@torch.no_grad()
def recon_metrics(ae, loader, max_batches=10):
    ae.eval(); ps, ss = [], []
    for i,(cor, clean) in enumerate(loader):
        if i >= max_batches: break
        cor, clean = cor.to(device), clean.to(device)
        out = ae(cor)
        ps.append(psnr_fn(out, clean).item())
        ss.append(ssim_fn(out, clean).item())
    return float(np.mean(ps)), float(np.mean(ss))

for w in SWEEP_WIDTHS:
    p, s = recon_metrics(aes[w], pair_val)
    print(f"width={w:3d}  PSNR={p:.2f}  SSIM={s:.4f}")

# visual: corrupted -> recovered -> clean for the largest AE
ae = aes[SWEEP_WIDTHS[-1]]; ae.eval()
cor, clean = next(iter(pair_val)); cor, clean = cor.to(device), clean.to(device)
with torch.no_grad(): rec = ae(cor)
fig, axes = plt.subplots(3, 5, figsize=(12, 7))
for j in range(5):
    axes[0,j].imshow(cor[j].cpu().permute(1,2,0)); axes[0,j].axis("off")
    axes[1,j].imshow(rec[j].cpu().permute(1,2,0)); axes[1,j].axis("off")
    axes[2,j].imshow(clean[j].cpu().permute(1,2,0)); axes[2,j].axis("off")
axes[0,0].set_ylabel("corrupted"); axes[1,0].set_ylabel("recovered"); axes[2,0].set_ylabel("clean")
plt.suptitle(f"Recovery AE (width={SWEEP_WIDTHS[-1]})"); plt.tight_layout(); plt.show()

import torch, time

@torch.no_grad()
def latency_ms(ae, n=200):
    ae.eval()
    x = torch.randn(1,3,64,64, device=device)
    for _ in range(10): ae(x)                       # warmup
    if device=="cuda": torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(n): ae(x)
    if device=="cuda": torch.cuda.synchronize()
    return (time.time()-t0)/n*1000

cost = {}
for w in SWEEP_WIDTHS:
    cost[w] = {"params": count_params(aes[w]), "latency_ms": latency_ms(aes[w])}
    print(f"width={w:3d}  params={cost[w]['params']:,}  latency={cost[w]['latency_ms']:.3f} ms")

import torch.nn as nn
from torchvision import models

def build_mobilenet(n):
    m = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
    m.classifier[1] = nn.Linear(m.classifier[1].in_features, n)
    return m

clf = build_mobilenet(n_classes).to(device)
ck = torch.load("/content/baseline1_mobilenet.pt", map_location=device)
clf.load_state_dict(ck["model"]); clf.eval()
for p in clf.parameters(): p.requires_grad = False   # FROZEN
print("frozen Baseline 1 loaded")

IMAGENET_MEAN = torch.tensor([0.485,0.456,0.406], device=device).view(1,3,1,1)
IMAGENET_STD  = torch.tensor([0.229,0.224,0.225], device=device).view(1,3,1,1)
def imagenet_norm(x01): return (x01 - IMAGENET_MEAN) / IMAGENET_STD   # x in [0,1]

import numpy as np, torch
from sklearn.metrics import balanced_accuracy_score
from torch.utils.data import Dataset, DataLoader
from PIL import Image

class RawCorruptDS(Dataset):
    """Returns (corrupted_[0,1]_tensor, label). No norm — pipeline handles it."""
    def __init__(self, raw, c, s): self.raw, self.c, self.s = raw, c, s
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        cor = corrupt(img, self.c, self.s)
        t = torch.from_numpy(cor).float().permute(2,0,1)/255.0
        return t, int(np.asarray(lab).squeeze())

@torch.no_grad()
def eval_pipeline(ae, corruption, severity, clf):
    """ae=None means no recovery (baseline path)."""
    loader = DataLoader(RawCorruptDS(test_raw, corruption, severity),
                        batch_size=128, shuffle=False, num_workers=2)
    ys, ps = [], []
    for x01, y in loader:
        x01 = x01.to(device)
        if ae is not None: x01 = ae(x01)
        logits = clf(imagenet_norm(x01))
        ps += logits.argmax(1).cpu().tolist(); ys += y.tolist()
    return float(balanced_accuracy_score(ys, ps))

@torch.no_grad()
def eval_pipeline_clean(ae, clf):
    """Clean-accuracy preservation check (Paper B failure mode)."""
    ys, ps = [], []
    for img_i in range(len(test_raw)):
        pass
    # batch version:
    from torch.utils.data import DataLoader
    class RawCleanDS(Dataset):
        def __len__(s): return len(test_raw)
        def __getitem__(s,i):
            img,lab=test_raw[i]
            return torch.from_numpy(np.array(img)).float().permute(2,0,1)/255.0, int(np.asarray(lab).squeeze())
    loader = DataLoader(RawCleanDS(), batch_size=128, shuffle=False, num_workers=2)
    for x01,y in loader:
        x01=x01.to(device)
        if ae is not None: x01=ae(x01)
        ps += clf(imagenet_norm(x01)).argmax(1).cpu().tolist(); ys += y.tolist()
    return float(balanced_accuracy_score(ys,ps))

EVAL_CORRUPTIONS = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]
EVAL_SEVERITIES  = [0, 2, 4]      # 4 is UNSEEN by the AE (trained on 0-2)

pipe_results = {}   # pipe_results[width][cond] = balanced acc
for w in SWEEP_WIDTHS:
    pipe_results[w] = {}
    pipe_results[w]["clean"] = eval_pipeline_clean(aes[w], clf)
    for c in EVAL_CORRUPTIONS:
        for s in EVAL_SEVERITIES:
            pipe_results[w][f"{c}_sev{s}"] = eval_pipeline(aes[w], c, s, clf)
    print(f"width={w} done | clean={pipe_results[w]['clean']:.3f}")

import pandas as pd, torch.nn.functional as F

# Non-learned baseline "recovery": gaussian blur as a cheap denoiser (~0 params)
class Medianish(nn.Module):
    def forward(self, x):   # 3x3 average filter as a trivial denoiser
        k = torch.ones(3,1,3,3, device=x.device)/9.0
        return torch.clamp(F.conv2d(x, k, padding=1, groups=3), 0, 1)
classical = Medianish().to(device)

best_w = SWEEP_WIDTHS[-1]   # use largest AE for the headline ablation row
conds = ["clean"] + [f"{c}_sev{s}" for c in EVAL_CORRUPTIONS for s in EVAL_SEVERITIES]

abl = {"condition": conds}
abl["B1_frozen_no_recovery"] = [baseline1_bal[c] for c in conds]
abl["B2_aug_trained"]        = [aug_results[c]["bal"] for c in conds]   # from Day 3
abl["classical_denoise"]     = [eval_pipeline_clean(classical, clf) if c=="clean"
                                else eval_pipeline(classical, c.rsplit("_sev",1)[0], int(c[-1]), clf)
                                for c in conds]
abl["recovery_AE_ours"]      = [pipe_results[best_w][c] for c in conds]

abl_df = pd.DataFrame(abl)
abl_df.to_csv("/content/day5_ablation.csv", index=False)
print("saved -> /content/day5_ablation.csv")
abl_df

import torch
ae = aes[4]; ae.eval()

# grab one clean test batch, run through AE, inspect
class RawCleanDS(torch.utils.data.Dataset):
    def __len__(s): return len(test_raw)
    def __getitem__(s,i):
        img,lab=test_raw[i]
        return torch.from_numpy(np.array(img)).float().permute(2,0,1)/255.0, int(np.asarray(lab).squeeze())
loader = torch.utils.data.DataLoader(RawCleanDS(), batch_size=64, shuffle=False)
x01, y = next(iter(loader)); x01 = x01.to(device)

with torch.no_grad():
    rec = ae(x01)
    print("AE output range:", rec.min().item(), "to", rec.max().item())   # should be ~0 to 1
    logits1 = clf((rec - IMN_MEAN)/IMN_STD)
    logits2 = clf2((rec - IMN_MEAN)/IMN_STD)
    print("clf1 preds on AE output:", torch.bincount(logits1.argmax(1), minlength=2).tolist())
    print("clf2 preds on AE output:", torch.bincount(logits2.argmax(1), minlength=2).tolist())
    print("clf2 preds on RAW clean:", torch.bincount(clf2((x01-IMN_MEAN)/IMN_STD).argmax(1), minlength=2).tolist())

# reload B2 cleanly
clf2 = build_mobilenet(n_classes).to(device)
ck2 = torch.load("/content/baseline2_aug_mobilenet.pt", map_location=device)
clf2.load_state_dict(ck2["model"]); clf2.eval()
for p in clf2.parameters(): p.requires_grad = False

@torch.no_grad()
def eval_pipeline_on(clf_model, ae, corruption, severity):
    loader = DataLoader(RawCorruptDS(test_raw, corruption, severity),
                        batch_size=128, shuffle=False, num_workers=2)
    ys, ps = [], []
    for x01, y in loader:
        x01 = x01.to(device)
        if ae is not None: x01 = ae(x01)
        ps += clf_model((x01 - IMN_MEAN)/IMN_STD).argmax(1).cpu().tolist()
        ys += y.tolist()
    return float(balanced_accuracy_score(ys, ps))

@torch.no_grad()
def eval_clean_on(clf_model, ae):
    class RawCleanDS(Dataset):
        def __len__(s): return len(test_raw)
        def __getitem__(s,i):
            img,lab=test_raw[i]
            return torch.from_numpy(np.array(img)).float().permute(2,0,1)/255.0, int(np.asarray(lab).squeeze())
    loader = DataLoader(RawCleanDS(), batch_size=128, shuffle=False, num_workers=2)
    ys, ps = [], []
    for x01,y in loader:
        x01=x01.to(device)
        if ae is not None: x01=ae(x01)
        ps += clf_model((x01-IMN_MEAN)/IMN_STD).argmax(1).cpu().tolist(); ys += y.tolist()
    return float(balanced_accuracy_score(ys,ps))

# sanity check FIRST: B2 with NO AE should reproduce your Day 3 aug numbers (~0.90 clean)
print("SANITY clf2 no-AE clean:", eval_clean_on(clf2, None))   # expect ~0.90
print("SANITY clf2 no-AE noise_sev2:", eval_pipeline_on(clf2, None, "gaussian_noise", 2))  # expect ~0.78

best_w = 4   # the winning lightweight AE
import pandas as pd
conds = ["clean"] + [f"{c}_sev{s}" for c in EVAL_CORRUPTIONS for s in EVAL_SEVERITIES]
stack = {"condition": conds, "B2_aug_only": [aug_results[c]["bal"] for c in conds]}
stack["AE_plus_aug"] = [eval_clean_on(clf2, aes[best_w]) if c=="clean"
                        else eval_pipeline_on(clf2, aes[best_w], c.rsplit("_sev",1)[0], int(c[-1]))
                        for c in conds]
stack_df = pd.DataFrame(stack)
stack_df["complementary_gain"] = stack_df["AE_plus_aug"] - stack_df["B2_aug_only"]
stack_df

import matplotlib.pyplot as plt, numpy as np

# average recovery gain over corrupted conditions (vs frozen Baseline 1), per width
corr_conds = [c for c in conds if c != "clean"]
gain_per_w, params_per_w, lat_per_w, clean_per_w = [], [], [], []
for w in SWEEP_WIDTHS:
    gains = [pipe_results[w][c] - baseline1_bal[c] for c in corr_conds]
    gain_per_w.append(np.mean(gains))
    params_per_w.append(cost[w]["params"])
    lat_per_w.append(cost[w]["latency_ms"])
    clean_per_w.append(pipe_results[w]["clean"])

fig, ax = plt.subplots(1, 2, figsize=(13, 4.8))
ax[0].plot(params_per_w, gain_per_w, "o-", color="#1565C0")
for w,x,y in zip(SWEEP_WIDTHS, params_per_w, gain_per_w):
    ax[0].annotate(f"w={w}", (x,y), textcoords="offset points", xytext=(6,4), fontsize=8)
ax[0].set_xscale("log"); ax[0].set_xlabel("AE parameters (log)")
ax[0].set_ylabel("mean recovery gain (balanced acc)")
ax[0].set_title("Main RQ: recovery gain vs model size")

ax[1].plot(lat_per_w, gain_per_w, "s-", color="#2E7D32")
for w,x,y in zip(SWEEP_WIDTHS, lat_per_w, gain_per_w):
    ax[1].annotate(f"w={w}", (x,y), textcoords="offset points", xytext=(6,4), fontsize=8)
ax[1].set_xlabel("inference latency (ms/image)")
ax[1].set_ylabel("mean recovery gain")
ax[1].set_title("Recovery gain vs latency")
plt.tight_layout(); plt.savefig("/content/day5_pareto.png", dpi=150, bbox_inches="tight"); plt.show()

print("clean-accuracy preservation per width (should stay near", round(baseline1_bal['clean'],3),"):")
for w,cl in zip(SWEEP_WIDTHS, clean_per_w): print(f"  w={w}: {cl:.3f}")

import numpy as np, torch
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import balanced_accuracy_score

def corrupt_compound(pil_img, name1, sev1, name2, sev2):
    """Apply two corruptions in sequence."""
    from PIL import Image
    step1 = corrupt(pil_img, name1, sev1)              # uint8 HxWx3
    step2 = corrupt(Image.fromarray(step1), name2, sev2)
    return step2

class CompoundDS(Dataset):
    def __init__(self, raw, n1, s1, n2, s2):
        self.raw, self.n1, self.s1, self.n2, self.s2 = raw, n1, s1, n2, s2
    def __len__(self): return len(self.raw)
    def __getitem__(self, i):
        img, lab = self.raw[i]
        cor = corrupt_compound(img, self.n1, self.s1, self.n2, self.s2)
        t = torch.from_numpy(cor).float().permute(2,0,1)/255.0
        return t, int(np.asarray(lab).squeeze())

@torch.no_grad()
def eval_compound(ae, n1, s1, n2, s2, clf):
    loader = DataLoader(CompoundDS(test_raw, n1, s1, n2, s2),
                        batch_size=128, shuffle=False, num_workers=2)
    ys, ps = [], []
    for x01, y in loader:
        x01 = x01.to(device)
        if ae is not None: x01 = ae(x01)
        ps += clf((x01 - IMN_MEAN)/IMN_STD).argmax(1).cpu().tolist()
        ys += y.tolist()
    return float(balanced_accuracy_score(ys, ps))

best_w = 4
COMPOUND_PAIRS = [
    ("gaussian_noise", 2, "gaussian_blur", 2),
    ("gaussian_blur", 2, "jpeg_compression", 2),
    ("gaussian_noise", 2, "jpeg_compression", 2),
]

import pandas as pd
rows = []
for n1, s1, n2, s2 in COMPOUND_PAIRS:
    no_rec = eval_compound(None,        n1, s1, n2, s2, clf)
    rec    = eval_compound(aes[best_w], n1, s1, n2, s2, clf)
    rows.append({"compound": f"{n1}+{n2}", "no_recovery": no_rec,
                 "with_recovery": rec, "recovery_gain": rec - no_rec})
    print(f"{n1}+{n2}: no_rec={no_rec:.3f}  rec={rec:.3f}  gain={rec-no_rec:+.3f}")

compound_df = pd.DataFrame(rows)
compound_df.to_csv("/content/day6_compound.csv", index=False)
compound_df

# Kermany Chest X-Ray (Cell et al.) — via Kaggle. Two common routes:
# Route A: if you have a kaggle.json uploaded
import os
print("Attempting Kermany download...")

# Easiest in Colab: use kagglehub (no manual API key needed for public datasets in many cases)
!pip install -q kagglehub
import kagglehub
try:
    path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")
    print("downloaded to:", path)
    KERMANY_DIR = path
except Exception as e:
    print("kagglehub failed:", e)
    print("Fallback: upload kaggle.json via the Files panel, then run:")
    print("  !mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json")
    print("  !kaggle datasets download -d paultimothymooney/chest-xray-pneumonia -p /content --unzip")
    KERMANY_DIR = "/content/chest_xray"

# locate the test split
import glob
candidates = glob.glob(os.path.join(KERMANY_DIR, "**", "test"), recursive=True)
print("test dir candidates:", candidates)

import os, glob, numpy as np, torch
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import balanced_accuracy_score

KERMANY_TEST = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"

# build (path, label) list — NORMAL=0, PNEUMONIA=1 to match PneumoniaMNIST
kermany_items = []
for cls_name, lab in [("NORMAL", 0), ("PNEUMONIA", 1)]:
    files = glob.glob(os.path.join(KERMANY_TEST, cls_name, "*.jpeg")) + \
            glob.glob(os.path.join(KERMANY_TEST, cls_name, "*.jpg")) + \
            glob.glob(os.path.join(KERMANY_TEST, cls_name, "*.png"))
    kermany_items += [(f, lab) for f in files]
    print(f"{cls_name}: {len(files)} images")
print("total:", len(kermany_items))

class KermanyDS(Dataset):
    """Full-res grayscale X-ray -> 64x64 RGB [0,1], matching the training pipeline.
       corruption=None means clean; otherwise apply (name, severity)."""
    def __init__(self, items, corruption=None, severity=None):
        self.items, self.c, self.s = items, corruption, severity
    def __len__(self): return len(self.items)
    def __getitem__(self, i):
        path, lab = self.items[i]
        img = Image.open(path).convert("RGB").resize((64, 64))   # grayscale->RGB, match size
        if self.c is not None:
            from PIL import Image as PILImage
            arr = corrupt(img, self.c, self.s)                   # uint8
            img = PILImage.fromarray(arr)
        t = torch.from_numpy(np.array(img)).float().permute(2,0,1)/255.0
        return t, lab

@torch.no_grad()
def eval_kermany(ae, corruption, severity, clf):
    ds = KermanyDS(kermany_items, corruption, severity)
    loader = DataLoader(ds, batch_size=128, shuffle=False, num_workers=2)
    ys, ps = [], []
    for x01, y in loader:
        x01 = x01.to(device)
        if ae is not None: x01 = ae(x01)
        ps += clf((x01 - IMN_MEAN)/IMN_STD).argmax(1).cpu().tolist()
        ys += y.tolist()
    return float(balanced_accuracy_score(ys, ps))

best_w = 4
TRANSFER_CORRUPTION, TRANSFER_SEV = "gaussian_noise", 2   # representative

import pandas as pd
clean_norec = eval_kermany(None,        None, None,                       clf)
clean_rec   = eval_kermany(aes[best_w], None, None,                       clf)
corr_norec  = eval_kermany(None,        TRANSFER_CORRUPTION, TRANSFER_SEV, clf)
corr_rec    = eval_kermany(aes[best_w], TRANSFER_CORRUPTION, TRANSFER_SEV, clf)

print(f"{'':18s}{'no recovery':>14s}{'with recovery':>15s}")
print(f"{'clean':18s}{clean_norec:>14.3f}{clean_rec:>15.3f}")
print(f"{'corrupted':18s}{corr_norec:>14.3f}{corr_rec:>15.3f}")
print(f"\nTRANSFER recovery gain (corrupted): {corr_rec - corr_norec:+.3f}")
print(f"Compare to in-domain noise_sev2 gain: ~{0.732 - 0.500:+.3f}")

transfer_df = pd.DataFrame([
    {"condition": "clean",     "no_recovery": clean_norec, "with_recovery": clean_rec},
    {"condition": "corrupted", "no_recovery": corr_norec,  "with_recovery": corr_rec},
])
transfer_df["recovery_gain"] = transfer_df["with_recovery"] - transfer_df["no_recovery"]
transfer_df.to_csv("/content/day6_kermany_transfer.csv", index=False)
transfer_df

"""
# Results section"""

import numpy as np, matplotlib.pyplot as plt
from PIL import Image

clean_pil = train_raw[0][0]
show_corruptions = ["gaussian_noise", "gaussian_blur", "jpeg_compression"]
show_sevs = [0, 2, 4]

fig, axes = plt.subplots(len(show_corruptions), len(show_sevs)+1, figsize=(11, 8))
for r, c in enumerate(show_corruptions):
    axes[r,0].imshow(np.array(clean_pil)); axes[r,0].axis("off")
    if r==0: axes[r,0].set_title("clean", fontsize=10)
    axes[r,0].set_ylabel(c, fontsize=10, rotation=90, labelpad=10)
    for k, s in enumerate(show_sevs):
        axes[r,k+1].imshow(corrupt(clean_pil, c, s)); axes[r,k+1].axis("off")
        if r==0: axes[r,k+1].set_title(f"severity {s}", fontsize=10)
plt.suptitle("Fig 1 — MedMNIST-C corruptions on PneumoniaMNIST (64×64)", fontsize=12)
plt.tight_layout(); plt.savefig("/content/fig1_corruptions.png", dpi=150, bbox_inches="tight"); plt.show()

import matplotlib.pyplot as plt, numpy as np

conds = ["clean"] + [f"{c}_sev{s}" for c in ["gaussian_noise","gaussian_blur","jpeg_compression"] for s in [0,2,4]]
labels = [c.replace("_sev","\ns").replace("gaussian_","g_").replace("jpeg_compression","jpeg") for c in conds]
b1  = [baseline1_bal[c] for c in conds]
b2  = [aug_results[c]["bal"] for c in conds]
rec = [pipe_results[4][c] for c in conds]

x = np.arange(len(conds)); w = 0.27
fig, ax = plt.subplots(figsize=(13, 5))
ax.bar(x-w, b1,  w, label="Baseline 1 (clean-trained, frozen)", color="#C62828")
ax.bar(x,   rec, w, label="+ Recovery AE (w=4, ~1k params)",     color="#1565C0")
ax.bar(x+w, b2,  w, label="Baseline 2 (aug-trained, Paper A)",   color="#2E7D32")
ax.axhline(0.5, ls=":", c="gray", label="chance")
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel("balanced accuracy"); ax.set_ylim(0,1)
ax.set_title("Fig 2 — Collapse and recovery: a 1k-param module lifts a frozen classifier off chance")
ax.legend(fontsize=8, loc="lower right")
plt.tight_layout(); plt.savefig("/content/fig2_collapse_recovery.png", dpi=150, bbox_inches="tight"); plt.show()

import matplotlib.pyplot as plt, numpy as np

conds = ["clean"] + [f"{c}_sev{s}" for c in ["gaussian_noise","gaussian_blur","jpeg_compression"] for s in [0,2,4]]
labels = [c.replace("_sev","\ns").replace("gaussian_","g_").replace("jpeg_compression","jpeg") for c in conds]
b1  = [baseline1_bal[c] for c in conds]
b2  = [aug_results[c]["bal"] for c in conds]
rec = [pipe_results[4][c] for c in conds]

x = np.arange(len(conds)); w = 0.27
fig, ax = plt.subplots(figsize=(13, 5))
ax.bar(x-w, b1,  w, label="Baseline 1 (clean-trained, frozen)", color="#C62828")
ax.bar(x,   rec, w, label="+ Recovery AE (w=4, ~1k params)",     color="#1565C0")
ax.bar(x+w, b2,  w, label="Baseline 2 (aug-trained, Paper A)",   color="#2E7D32")
ax.axhline(0.5, ls=":", c="gray", label="chance")
ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
ax.set_ylabel("balanced accuracy"); ax.set_ylim(0,1)
ax.set_title("Fig 2 — Collapse and recovery: a 1k-param module lifts a frozen classifier off chance")
ax.legend(fontsize=8, loc="lower right")
plt.tight_layout(); plt.savefig("/content/fig2_collapse_recovery.png", dpi=150, bbox_inches="tight"); plt.show()

import torch, numpy as np, matplotlib.pyplot as plt
from torch.utils.data import DataLoader

ae = aes[4]; ae.eval()
# reuse PairLabelDS to grab a varied batch
batch = next(iter(DataLoader(PairLabelDS(val_raw, TRAIN_CORRUPTIONS, TRAIN_SEVERITIES), batch_size=6, shuffle=True)))
cor, clean, _ = batch
with torch.no_grad(): rec = ae(cor.to(device)).cpu()

fig, axes = plt.subplots(3, 6, figsize=(13, 7))
for j in range(6):
    axes[0,j].imshow(cor[j].permute(1,2,0)); axes[0,j].axis("off")
    axes[1,j].imshow(rec[j].permute(1,2,0)); axes[1,j].axis("off")
    axes[2,j].imshow(clean[j].permute(1,2,0)); axes[2,j].axis("off")
for r, lbl in enumerate(["corrupted","recovered (w=4)","clean target"]):
    axes[r,0].set_ylabel(lbl, fontsize=10)
plt.suptitle("Fig 3 — Recovery autoencoder reconstructions", fontsize=12)
plt.tight_layout(); plt.savefig("/content/fig3_reconstructions.png", dpi=150, bbox_inches="tight"); plt.show()

import matplotlib.pyplot as plt, numpy as np

corr_conds = [c for c in conds if c != "clean"]
gain = [np.mean([pipe_results[w][c]-baseline1_bal[c] for c in corr_conds]) for w in SWEEP_WIDTHS]
params = [cost[w]["params"] for w in SWEEP_WIDTHS]
clean_pres = [pipe_results[w]["clean"] for w in SWEEP_WIDTHS]

fig, ax = plt.subplots(figsize=(8,5))
sc = ax.scatter(params, gain, s=120, c=clean_pres, cmap="viridis", zorder=3, edgecolor="k")
ax.plot(params, gain, "--", c="gray", zorder=2)
for w,xp,yp in zip(SWEEP_WIDTHS, params, gain):
    ax.annotate(f"w={w}\n{cost[w]['params']:,}p", (xp,yp), textcoords="offset points",
                xytext=(8,-4), fontsize=8)
ax.set_xscale("log"); ax.set_xlabel("AE parameters (log scale)")
ax.set_ylabel("mean recovery gain (balanced acc vs Baseline 1)")
ax.set_title("Fig 4 [MAIN RQ] — Lightweight recovery: smallest model gives the best gain")
plt.colorbar(sc, label="clean-accuracy preservation")
plt.tight_layout(); plt.savefig("/content/fig4_pareto.png", dpi=150, bbox_inches="tight"); plt.show()
print("Knee/best point: w=4 with", f"{cost[4]['params']:,}", "params, gain =", f"{gain[0]:.3f}")

import matplotlib.pyplot as plt, numpy as np

fig, ax = plt.subplots(1, 2, figsize=(13, 4.5))

# left: compound corruptions
cl = [r.replace("gaussian_","g_").replace("jpeg_compression","jpeg") for r in compound_df["compound"]]
xc = np.arange(len(cl)); w=0.38
ax[0].bar(xc-w/2, compound_df["no_recovery"], w, label="no recovery", color="#C62828")
ax[0].bar(xc+w/2, compound_df["with_recovery"], w, label="with recovery", color="#1565C0")
ax[0].axhline(0.5, ls=":", c="gray")
ax[0].set_xticks(xc); ax[0].set_xticklabels(cl, fontsize=8)
ax[0].set_ylabel("balanced accuracy"); ax[0].set_ylim(0,1)
ax[0].set_title("Sub-Q1: unseen compound corruptions"); ax[0].legend(fontsize=8)

# right: Kermany transfer
tl = transfer_df["condition"].tolist()
xt = np.arange(len(tl))
ax[1].bar(xt-w/2, transfer_df["no_recovery"], w, label="no recovery", color="#C62828")
ax[1].bar(xt+w/2, transfer_df["with_recovery"], w, label="with recovery", color="#1565C0")
ax[1].axhline(0.5, ls=":", c="gray")
ax[1].set_xticks(xt); ax[1].set_xticklabels(tl, fontsize=9)
ax[1].set_ylim(0,1); ax[1].set_title("Sub-Q2: Kermany real-world transfer"); ax[1].legend(fontsize=8)

plt.suptitle("Fig 5 — Generalization: recovery holds on unseen corruptions and a new domain", fontsize=12)
plt.tight_layout(); plt.savefig("/content/fig5_generalization.png", dpi=150, bbox_inches="tight"); plt.show()

summary = f"""
CSE 6207 — PROGRESS SUMMARY
Lightweight Test-Time Image Recovery for Robust Medical Image Classification

SETUP
- Dataset: PneumoniaMNIST (64x64 RGB). Corruptions: official MedMNIST-C registry (Paper A).
- Classifier: MobileNetV2, ImageNet-pretrained. Metric: balanced accuracy (dataset is imbalanced;
  raw accuracy hides collapse-to-majority).
- Recovery: convolutional autoencoder in front of a FROZEN classifier, trained with a
  perceptual loss = MSE(recon, clean) + lambda * CE(frozen_clf(recon), label). Trained on single
  corruptions, severities 0-2 (severity 4 held out as unseen).

KEY NUMBERS
- Baseline 1 (clean-trained) collapses under corruption: clean {baseline1_bal['clean']:.3f}
  -> gaussian_noise {baseline1_bal['gaussian_noise_sev2']:.3f} (chance = 0.50).
- Baseline 2 (MedMNIST-C augmentation, Paper A replicated): recovers strongly,
  e.g. noise_sev2 {aug_results['gaussian_noise_sev2']['bal']:.3f}.
- Recovery AE (w=4, {cost[4]['params']:,} params): lifts frozen classifier from 0.50 to
  ~0.74 across noise/blur/jpeg, INCLUDING unseen severity 4.
- Ablation: learned AE (~0.74) >> classical 3x3 denoiser (~0.50-0.65). Learned approach justified.
- MAIN RQ / Pareto: smallest model (w=4) gives the BEST mean recovery gain
  ({np.mean([pipe_results[4][c]-baseline1_bal[c] for c in corr_conds]):.3f}); gain does not increase
  with capacity. Lightweight recovery is not just feasible but optimal here.

SUB-QUESTIONS
- Sub-Q1 (compound, unseen): positive recovery gain on all stacked pairs (+0.16 to +0.24).
- Sub-Q2 (Kermany transfer): recovery gain on real-world X-rays = {transfer_df.iloc[1]['recovery_gain']:+.3f},
  identical to in-domain gain. Strategy generalizes beyond the training domain.

WHAT WORKED / WHAT DIDN'T
- WORKED: a ~1k-param AE recovers a frozen classifier from chance to ~0.74; result is consistent
  across single corruptions, compound corruptions, and a new dataset (recurring ~0.73 plateau ->
  the module learns a generic projection toward the clean manifold, not corruption-specific fixes).
- MSE-only training FAILED (learned identity mapping, 0.50 on noise); perceptual loss was essential.
- LIMITATION 1: recovery is classifier-coupled. An AE trained against classifier A does not transfer
  to classifier B (B collapses on A's recovered images). Recovery is tuned to its guidance classifier.
- LIMITATION 2: on CLEAN input, the AE mildly REDUCES accuracy (Kermany clean
  {transfer_df.iloc[0]['no_recovery']:.3f} -> {transfer_df.iloc[0]['with_recovery']:.3f}).
  Motivates a corruption-gating detector (future work).

FRAMING
- Contribution is NOT "beats augmentation" (it doesn't). It is: retraining-free, corruption-agnostic,
  compute-bounded recovery for a FIXED classifier - a different mechanism than augmentation, useful
  where the classifier cannot be retouched. Lineage: test-time recovery (Gao et al. CVPR'23;
  Decorruptor ECCV'24), instantiated at ~1k params instead of a diffusion model.
"""
print(summary)
with open("/content/progress_summary.txt", "w") as f: f.write(summary)
print("\nsaved -> /content/progress_summary.txt")